"""Phase 8.5 SESS-04 — predicate API consumed by Phase 9 StrategyRouter.

Per CONTEXT D-06 / D-07:
  is_tradeable_session(pair, strategy, timeframe, ts) -> bool  (hard veto)
  is_blackout_window(ts) -> bool                                (global ts-only filter)

Imports SESSION_RULES + BLACKOUT_PATTERNS from session_config (generated by
run_temporal_analysis.py per RESEARCH Pattern 6).
"""
from __future__ import annotations

from datetime import datetime, timedelta

from .session_config import SESSION_RULES, BLACKOUT_PATTERNS


def _pair_currencies(pair: str) -> list[str]:
    """USDJPY -> ['USD', 'JPY']."""
    if not pair or len(pair) != 6:
        return []
    return [pair[:3], pair[3:]]


def _matches_pattern(pattern: dict, ts: datetime) -> bool:
    """Resolve a parametric blackout pattern against a concrete UTC timestamp.

    Per CONTEXT D-01 — ts is assumed UTC.
    """
    ptype = pattern.get("pattern", "")
    time_utc = pattern.get("time_utc", (0, 0))
    if not isinstance(time_utc, (tuple, list)) or len(time_utc) != 2:
        return False
    hh, mm = int(time_utc[0]), int(time_utc[1])
    duration = int(pattern.get("duration_min", 30))
    start = ts.replace(hour=hh, minute=mm, second=0, microsecond=0)
    end = start + timedelta(minutes=duration)
    in_window = start <= ts < end

    if ptype == "wom":
        n_required = int(pattern.get("n", 0))
        dow_required = int(pattern.get("dow", -1))
        nth_dow = (ts.day - 1) // 7 + 1
        if nth_dow != n_required:
            return False
        if ts.weekday() != dow_required:
            return False
        return in_window

    if ptype == "dow":
        dow_required = int(pattern.get("dow", -1))
        if ts.weekday() != dow_required:
            return False
        return in_window

    if ptype == "mom":
        # Plan 04 emits 'n' for mom (Nth day); accept both for compatibility.
        day_required = int(pattern.get("day", pattern.get("n", 0)))
        if ts.day != day_required:
            return False
        return in_window

    if ptype == "yearly":
        m = int(pattern.get("month", 0))
        d = int(pattern.get("day", 0))
        if ts.month != m or ts.day != d:
            return False
        return in_window

    if ptype == "dates":
        dates = pattern.get("dates", []) or []
        day_str = ts.strftime("%Y-%m-%d")
        if day_str not in dates:
            return False
        return in_window

    return False


def is_tradeable_session(
    pair: str,
    strategy: str,
    timeframe: str,
    ts: datetime,
) -> bool:
    """CONTEXT D-06 — hard veto. False blocks entry; True permits (other gates may still reject).

    Logic:
      1. Look up SESSION_RULES[(pair, strategy, timeframe)]; if no rule, default True.
      2. If ts.hour in blacklisted_hours -> False
      3. If ts.weekday() in blacklisted_dows -> False
      4. If any BLACKOUT_PATTERNS matches AND pattern.affects intersects pair currencies -> False
      5. Otherwise True
    """
    rule = SESSION_RULES.get((pair, strategy, timeframe))
    if rule is not None:
        if ts.hour in rule.get("blacklisted_hours", []):
            return False
        if ts.weekday() in rule.get("blacklisted_dows", []):
            return False

    affected = set(_pair_currencies(pair))
    for pattern in BLACKOUT_PATTERNS:
        pat_affects = set(pattern.get("affects", []) or [])
        if pat_affects and not (affected & pat_affects):
            continue
        if _matches_pattern(pattern, ts):
            return False
    return True


def is_blackout_window(ts: datetime) -> bool:
    """CONTEXT D-07 — global ts-only filter (currency-agnostic)."""
    return any(_matches_pattern(p, ts) for p in BLACKOUT_PATTERNS)


__all__ = ["is_tradeable_session", "is_blackout_window"]
